releasedate: "2018-12-22"
sage: "SageMath"
logo: "pix/sage_logo_new_l_hc_edgy-nq8.png"
version: "8.5"
version_solaris_bin: None
version_src: "8.5"
git: "http://git.sagemath.org/sage.git/"
git_website: "https://github.com/sagemath/website"
webmaster_href: "mailto:harald+smo@schil.ly"

# the docroot is the base URL for the documentation.
# the directory structure is (more or less) the same as in SageMath's "output" directory in doc
docroot: "http://doc.sagemath.org"
