releasedate: 2014-08-10
releasedate_devel: 2013-12-21
sage: Sage
logo: pix/sage_logo_new_l_hc_edgy-nq8.png
version: 6.3
version_devel: 6.1.beta1
version_solaris_bin: None
version_src: 6.3
git: http://git.sagemath.org/sage.git/
git_website: https://github.com/sagemath/website
webmaster_href: >
    http://mailhide.recaptcha.net/d?
    k=01JhWPFLZ8tJCbx84EXp20vw==&amp;c=C8CP83g7M5hbfmYWTynnLHz_lr5sWlI4Z2wKwgSaJ50="
    onclick="window.open(&#39;http://mailhide.recaptcha.net/d?
    k=01JhWPFLZ8tJCbx84EXp20vw==&amp;c=C8CP83g7M5hbfmYWTynnLHz_lr5sWlI4Z2wKwgSaJ50=&#39;
    , &#39;&#39;, &#39;toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300&#39;);
    return false;